language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - tools
    - android-23
    - android-24
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-24

env:
  - API=23
  - API=24

before_script:
  - script/run_emulator

after_script:
  - adb logcat -d
  - cat app/build/reports/lint-results.xml

notifications:
  slack: userfeeds:AsvcCusl8zszBQXwkToCYZzY
